branches:
  only:
    - master
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - coverage run --omit='./plexrequests/wsgi.py' --source='.' manage.py test

after_success:
  - codecov
